# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{cukeq}
  s.version = "0.0.1.dev"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jari Bakken"]
  s.date = %q{2010-11-30}
  s.default_executable = %q{cukeq}
  s.description = %q{Cucumber features distributed using AMQP.}
  s.email = %q{jari.bakken@gmail.com}
  s.executables = ["cukeq"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".autotest",
    ".document",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/cukeq",
    "features/cukeq.feature",
    "features/example1.feature",
    "features/example2.feature",
    "features/step_definitions/cukeq_steps.rb",
    "features/support/cukeq_helper.rb",
    "features/support/env.rb",
    "features/support/report_app.rb",
    "lib/cukeq.rb",
    "lib/cukeq/async_job.rb",
    "lib/cukeq/broker.rb",
    "lib/cukeq/em/system3.rb",
    "lib/cukeq/job_clearer.rb",
    "lib/cukeq/master.rb",
    "lib/cukeq/reporter.rb",
    "lib/cukeq/runner.rb",
    "lib/cukeq/scenario_exploder.rb",
    "lib/cukeq/scenario_runner.rb",
    "lib/cukeq/scm.rb",
    "lib/cukeq/scm/git_bridge.rb",
    "lib/cukeq/scm/shell_svn_bridge.rb",
    "lib/cukeq/scm/svn_bridge.rb",
    "lib/cukeq/slave.rb",
    "lib/cukeq/webapp.rb",
    "spec/cukeq/broker_spec.rb",
    "spec/cukeq/cukeq_spec.rb",
    "spec/cukeq/master_spec.rb",
    "spec/cukeq/reporter_spec.rb",
    "spec/cukeq/runner_spec.rb",
    "spec/cukeq/scenario_exploder_spec.rb",
    "spec/cukeq/scenario_runner_spec.rb",
    "spec/cukeq/scm/git_bridge_spec.rb",
    "spec/cukeq/scm/svn_bridge_spec.rb",
    "spec/cukeq/scm_spec.rb",
    "spec/cukeq/slave_spec.rb",
    "spec/cukeq/webapp_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/jarib/cukeq}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Distributed cucumbers}
  s.test_files = [
    "spec/cukeq/broker_spec.rb",
    "spec/cukeq/cukeq_spec.rb",
    "spec/cukeq/master_spec.rb",
    "spec/cukeq/reporter_spec.rb",
    "spec/cukeq/runner_spec.rb",
    "spec/cukeq/scenario_exploder_spec.rb",
    "spec/cukeq/scenario_runner_spec.rb",
    "spec/cukeq/scm/git_bridge_spec.rb",
    "spec/cukeq/scm/svn_bridge_spec.rb",
    "spec/cukeq/scm_spec.rb",
    "spec/cukeq/slave_spec.rb",
    "spec/cukeq/webapp_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<amqp>, [">= 0"])
      s.add_runtime_dependency(%q<thin>, [">= 0"])
      s.add_runtime_dependency(%q<json>, [">= 0"])
      s.add_runtime_dependency(%q<git>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 2.0.0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
      s.add_development_dependency(%q<rack-test>, [">= 0"])
      s.add_runtime_dependency(%q<amqp>, [">= 0"])
      s.add_runtime_dependency(%q<thin>, [">= 0"])
      s.add_runtime_dependency(%q<json>, [">= 0"])
      s.add_runtime_dependency(%q<git>, [">= 0"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 2.0.0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
      s.add_development_dependency(%q<rack-test>, [">= 0"])
    else
      s.add_dependency(%q<amqp>, [">= 0"])
      s.add_dependency(%q<thin>, [">= 0"])
      s.add_dependency(%q<json>, [">= 0"])
      s.add_dependency(%q<git>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 2.0.0"])
      s.add_dependency(%q<yard>, [">= 0"])
      s.add_dependency(%q<cucumber>, [">= 0"])
      s.add_dependency(%q<rack-test>, [">= 0"])
      s.add_dependency(%q<amqp>, [">= 0"])
      s.add_dependency(%q<thin>, [">= 0"])
      s.add_dependency(%q<json>, [">= 0"])
      s.add_dependency(%q<git>, [">= 0"])
      s.add_dependency(%q<nokogiri>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 2.0.0"])
      s.add_dependency(%q<yard>, [">= 0"])
      s.add_dependency(%q<cucumber>, [">= 0"])
      s.add_dependency(%q<rack-test>, [">= 0"])
    end
  else
    s.add_dependency(%q<amqp>, [">= 0"])
    s.add_dependency(%q<thin>, [">= 0"])
    s.add_dependency(%q<json>, [">= 0"])
    s.add_dependency(%q<git>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 2.0.0"])
    s.add_dependency(%q<yard>, [">= 0"])
    s.add_dependency(%q<cucumber>, [">= 0"])
    s.add_dependency(%q<rack-test>, [">= 0"])
    s.add_dependency(%q<amqp>, [">= 0"])
    s.add_dependency(%q<thin>, [">= 0"])
    s.add_dependency(%q<json>, [">= 0"])
    s.add_dependency(%q<git>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 2.0.0"])
    s.add_dependency(%q<yard>, [">= 0"])
    s.add_dependency(%q<cucumber>, [">= 0"])
    s.add_dependency(%q<rack-test>, [">= 0"])
  end
end

